[package]
name = "birdfeed"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
lettre = "0.11.19"
reqwest = "0.13.1"
rss = "2.0.12"
scraper = "0.25.0"
tokio = {version = "1.49.0", features = ["full"]}
